<?php

namespace PhpHelper;

class Countries
{
    /**
     * Countries array keyed by ISO and ISO3 codes with flag and name
     */
    public static $countries = [
        "AF"  => ["flag" => "🇦🇫", "name" => "Afghanistan"],
        "AFG" => ["flag" => "🇦🇫", "name" => "Afghanistan"],
        "AL"  => ["flag" => "🇦🇱", "name" => "Albania"],
        "ALB" => ["flag" => "🇦🇱", "name" => "Albania"],
        "DZ"  => ["flag" => "🇩🇿", "name" => "Algeria"],
        "DZA" => ["flag" => "🇩🇿", "name" => "Algeria"],
        "AS"  => ["flag" => "🇦🇸", "name" => "American Samoa"],
        "ASM" => ["flag" => "🇦🇸", "name" => "American Samoa"],
        "AD"  => ["flag" => "🇦🇩", "name" => "Andorra"],
        "AND" => ["flag" => "🇦🇩", "name" => "Andorra"],
        "AO"  => ["flag" => "🇦🇴", "name" => "Angola"],
        "AGO" => ["flag" => "🇦🇴", "name" => "Angola"],
        "AQ"  => ["flag" => "🇦🇶", "name" => "Antarctica"],
        "ATA" => ["flag" => "🇦🇶", "name" => "Antarctica"],
        "AI"  => ["flag" => "🇦🇮", "name" => "Anguilla"],
        "AIA" => ["flag" => "🇦🇮", "name" => "Anguilla"],
        "AG"  => ["flag" => "🇦🇬", "name" => "Antigua and Barbuda"],
        "ATG" => ["flag" => "🇦🇬", "name" => "Antigua and Barbuda"],
        "AR"  => ["flag" => "🇦🇷", "name" => "Argentina"],
        "ARG" => ["flag" => "🇦🇷", "name" => "Argentina"],
        "AM"  => ["flag" => "🇦🇲", "name" => "Armenia"],
        "ARM" => ["flag" => "🇦🇲", "name" => "Armenia"],
        "AW"  => ["flag" => "🇦🇼", "name" => "Aruba"],
        "ABW" => ["flag" => "🇦🇼", "name" => "Aruba"],
        "AX"  => ["flag" => "🇦🇽", "name" => "Åland Islands"],
        "ALA" => ["flag" => "🇦🇽", "name" => "Åland Islands"],
        "AU"  => ["flag" => "🇦🇺", "name" => "Australia"],
        "AUS" => ["flag" => "🇦🇺", "name" => "Australia"],
        "AT"  => ["flag" => "🇦🇹", "name" => "Austria"],
        "AUT" => ["flag" => "🇦🇹", "name" => "Austria"],
        "AZ"  => ["flag" => "🇦🇿", "name" => "Azerbaijan"],
        "AZE" => ["flag" => "🇦🇿", "name" => "Azerbaijan"],
        "BS"  => ["flag" => "🇧🇸", "name" => "Bahamas"],
        "BHS" => ["flag" => "🇧🇸", "name" => "Bahamas"],
        "BH"  => ["flag" => "🇧🇭", "name" => "Bahrain"],
        "BHR" => ["flag" => "🇧🇭", "name" => "Bahrain"],
        "BD"  => ["flag" => "🇧🇩", "name" => "Bangladesh"],
        "BGD" => ["flag" => "🇧🇩", "name" => "Bangladesh"],
        "BB"  => ["flag" => "🇧🇧", "name" => "Barbados"],
        "BRB" => ["flag" => "🇧🇧", "name" => "Barbados"],
        "BY"  => ["flag" => "🇧🇾", "name" => "Belarus"],
        "BLR" => ["flag" => "🇧🇾", "name" => "Belarus"],
        "BE"  => ["flag" => "🇧🇪", "name" => "Belgium"],
        "BEL" => ["flag" => "🇧🇪", "name" => "Belgium"],
        "BZ"  => ["flag" => "🇧🇿", "name" => "Belize"],
        "BLZ" => ["flag" => "🇧🇿", "name" => "Belize"],
        "BJ"  => ["flag" => "🇧🇯", "name" => "Benin"],
        "BEN" => ["flag" => "🇧🇯", "name" => "Benin"],
        "BL"  => ["flag" => "🇧🇱", "name" => "Saint Barthélemy"],
        "BLM" => ["flag" => "🇧🇱", "name" => "Saint Barthélemy"],
        "BM"  => ["flag" => "🇧🇲", "name" => "Bermuda"],
        "BMU" => ["flag" => "🇧🇲", "name" => "Bermuda"],
        "BT"  => ["flag" => "🇧🇹", "name" => "Bhutan"],
        "BTN" => ["flag" => "🇧🇹", "name" => "Bhutan"],
        "BO"  => ["flag" => "🇧🇴", "name" => "Bolivia"],
        "BOL" => ["flag" => "🇧🇴", "name" => "Bolivia"],
        "BQ"  => ["flag" => "🇧🇶", "name" => "Bonaire, Sint Eustatius and Saba"],
        "BES" => ["flag" => "🇧🇶", "name" => "Bonaire, Sint Eustatius and Saba"],
        "BA"  => ["flag" => "🇧🇦", "name" => "Bosnia and Herzegovina"],
        "BIH" => ["flag" => "🇧🇦", "name" => "Bosnia and Herzegovina"],
        "BW"  => ["flag" => "🇧🇼", "name" => "Botswana"],
        "BWA" => ["flag" => "🇧🇼", "name" => "Botswana"],
        "BR"  => ["flag" => "🇧🇷", "name" => "Brazil"],
        "BRA" => ["flag" => "🇧🇷", "name" => "Brazil"],
        "BV"  => ["flag" => "🇧🇻", "name" => "Bouvet Island"],
        "BVT" => ["flag" => "🇧🇻", "name" => "Bouvet Island"],
        "VG"  => ["flag" => "🇻🇬", "name" => "British Virgin Islands"],
        "VGB" => ["flag" => "🇻🇬", "name" => "British Virgin Islands"],
        "BN"  => ["flag" => "🇧🇳", "name" => "Brunei Darussalam"],
        "BRN" => ["flag" => "🇧🇳", "name" => "Brunei Darussalam"],
        "BG"  => ["flag" => "🇧🇬", "name" => "Bulgaria"],
        "BGR" => ["flag" => "🇧🇬", "name" => "Bulgaria"],
        "BF"  => ["flag" => "🇧🇫", "name" => "Burkina Faso"],
        "BFA" => ["flag" => "🇧🇫", "name" => "Burkina Faso"],
        "BI"  => ["flag" => "🇧🇮", "name" => "Burundi"],
        "BDI" => ["flag" => "🇧🇮", "name" => "Burundi"],
        "KH"  => ["flag" => "🇰🇭", "name" => "Cambodia"],
        "KHM" => ["flag" => "🇰🇭", "name" => "Cambodia"],
        "CM"  => ["flag" => "🇨🇲", "name" => "Cameroon"],
        "CMR" => ["flag" => "🇨🇲", "name" => "Cameroon"],
        "CA"  => ["flag" => "🇨🇦", "name" => "Canada"],
        "CAN" => ["flag" => "🇨🇦", "name" => "Canada"],
        "CC"  => ["flag" => "🇨🇨", "name" => "Cocos (Keeling) Islands"],
        "CCK" => ["flag" => "🇨🇨", "name" => "Cocos (Keeling) Islands"],
        "CV"  => ["flag" => "🇨🇻", "name" => "Cape Verde"],
        "CPV" => ["flag" => "🇨🇻", "name" => "Cape Verde"],
        "CF"  => ["flag" => "🇨🇫", "name" => "Central African Republic"],
        "CAF" => ["flag" => "🇨🇫", "name" => "Central African Republic"],
        "TD"  => ["flag" => "🇹🇩", "name" => "Chad"],
        "TCD" => ["flag" => "🇹🇩", "name" => "Chad"],
        "CL"  => ["flag" => "🇨🇱", "name" => "Chile"],
        "CHL" => ["flag" => "🇨🇱", "name" => "Chile"],
        "CN"  => ["flag" => "🇨🇳", "name" => "China"],
        "CHN" => ["flag" => "🇨🇳", "name" => "China"],
        "HK"  => ["flag" => "🇭🇰", "name" => "Hong Kong"],
        "HKG" => ["flag" => "🇭🇰", "name" => "Hong Kong"],
        "MO"  => ["flag" => "🇲🇴", "name" => "Macao"],
        "MAC" => ["flag" => "🇲🇴", "name" => "Macao"],
        "CO"  => ["flag" => "🇨🇴", "name" => "Colombia"],
        "COL" => ["flag" => "🇨🇴", "name" => "Colombia"],
        "KM"  => ["flag" => "🇰🇲", "name" => "Comoros"],
        "COM" => ["flag" => "🇰🇲", "name" => "Comoros"],
        "CG"  => ["flag" => "🇨🇬", "name" => "Congo"],
        "COG" => ["flag" => "🇨🇬", "name" => "Congo"],
        "CD"  => ["flag" => "🇨🇩", "name" => "Congo (Democratic Republic)"],
        "COD" => ["flag" => "🇨🇩", "name" => "Congo (Democratic Republic)"],
        "CR"  => ["flag" => "🇨🇷", "name" => "Costa Rica"],
        "CRI" => ["flag" => "🇨🇷", "name" => "Costa Rica"],
        "CI"  => ["flag" => "🇨🇮", "name" => "Côte d'Ivoire"],
        "CIV" => ["flag" => "🇨🇮", "name" => "Côte d'Ivoire"],
        "CK"  => ["flag" => "🇨🇰", "name" => "Cook Islands"],
        "COK" => ["flag" => "🇨🇰", "name" => "Cook Islands"],
        "HR"  => ["flag" => "🇭🇷", "name" => "Croatia"],
        "HRV" => ["flag" => "🇭🇷", "name" => "Croatia"],
        "CU"  => ["flag" => "🇨🇺", "name" => "Cuba"],
        "CUB" => ["flag" => "🇨🇺", "name" => "Cuba"],
        "CW"  => ["flag" => "🇨🇼", "name" => "Curaçao"],
        "CUW" => ["flag" => "🇨🇼", "name" => "Curaçao"],
        "CX"  => ["flag" => "🇨🇽", "name" => "Christmas Island"],
        "CXR" => ["flag" => "🇨🇽", "name" => "Christmas Island"],
        "CY"  => ["flag" => "🇨🇾", "name" => "Cyprus"],
        "CYP" => ["flag" => "🇨🇾", "name" => "Cyprus"],
        "CZ"  => ["flag" => "🇨🇿", "name" => "Czech Republic"],
        "CZE" => ["flag" => "🇨🇿", "name" => "Czech Republic"],
        "DK"  => ["flag" => "🇩🇰", "name" => "Denmark"],
        "DNK" => ["flag" => "🇩🇰", "name" => "Denmark"],
        "DJ"  => ["flag" => "🇩🇯", "name" => "Djibouti"],
        "DJI" => ["flag" => "🇩🇯", "name" => "Djibouti"],
        "DM"  => ["flag" => "🇩🇲", "name" => "Dominica"],
        "DMA" => ["flag" => "🇩🇲", "name" => "Dominica"],
        "DO"  => ["flag" => "🇩🇴", "name" => "Dominican Republic"],
        "DOM" => ["flag" => "🇩🇴", "name" => "Dominican Republic"],
        "EC"  => ["flag" => "🇪🇨", "name" => "Ecuador"],
        "ECU" => ["flag" => "🇪🇨", "name" => "Ecuador"],
        "EG"  => ["flag" => "🇪🇬", "name" => "Egypt"],
        "EGY" => ["flag" => "🇪🇬", "name" => "Egypt"],
        "EH"  => ["flag" => "🇪🇭", "name" => "Western Sahara"],
        "ESH" => ["flag" => "🇪🇭", "name" => "Western Sahara"],
        "SV"  => ["flag" => "🇸🇻", "name" => "El Salvador"],
        "SLV" => ["flag" => "🇸🇻", "name" => "El Salvador"],
        "SX"  => ["flag" => "🇸🇽", "name" => "Sint Maarten"],
        "SXM" => ["flag" => "🇸🇽", "name" => "Sint Maarten"],
        "GQ"  => ["flag" => "🇬🇶", "name" => "Equatorial Guinea"],
        "GNQ" => ["flag" => "🇬🇶", "name" => "Equatorial Guinea"],
        "ER"  => ["flag" => "🇪🇷", "name" => "Eritrea"],
        "ERI" => ["flag" => "🇪🇷", "name" => "Eritrea"],
        "EE"  => ["flag" => "🇪🇪", "name" => "Estonia"],
        "EST" => ["flag" => "🇪🇪", "name" => "Estonia"],
        "ET"  => ["flag" => "🇪🇹", "name" => "Ethiopia"],
        "ETH" => ["flag" => "🇪🇹", "name" => "Ethiopia"],
        "FO"  => ["flag" => "🇫🇴", "name" => "Faroe Islands"],
        "FRO" => ["flag" => "🇫🇴", "name" => "Faroe Islands"],
        "FJ"  => ["flag" => "🇫🇯", "name" => "Fiji"],
        "FJI" => ["flag" => "🇫🇯", "name" => "Fiji"],
        "FK"  => ["flag" => "🇫🇰", "name" => "Falkland Islands (Malvinas)"],
        "FLK" => ["flag" => "🇫🇰", "name" => "Falkland Islands (Malvinas)"],
        "FI"  => ["flag" => "🇫🇮", "name" => "Finland"],
        "FIN" => ["flag" => "🇫🇮", "name" => "Finland"],
        "FR"  => ["flag" => "🇫🇷", "name" => "France"],
        "FRA" => ["flag" => "🇫🇷", "name" => "France"],
        "GF"  => ["flag" => "🇬🇫", "name" => "French Guiana"],
        "GUF" => ["flag" => "🇬🇫", "name" => "French Guiana"],
        "GG"  => ["flag" => "🇬🇬", "name" => "Guernsey"],
        "GGY" => ["flag" => "🇬🇬", "name" => "Guernsey"],
        "PF"  => ["flag" => "🇵🇫", "name" => "French Polynesia"],
        "PYF" => ["flag" => "🇵🇫", "name" => "French Polynesia"],
        "GA"  => ["flag" => "🇬🇦", "name" => "Gabon"],
        "GAB" => ["flag" => "🇬🇦", "name" => "Gabon"],
        "GM"  => ["flag" => "🇬🇲", "name" => "Gambia"],
        "GMB" => ["flag" => "🇬🇲", "name" => "Gambia"],
        "GN"  => ["flag" => "🇬🇳", "name" => "Guinea"],
        "GIN" => ["flag" => "🇬🇳", "name" => "Guinea"],
        "GE"  => ["flag" => "🇬🇪", "name" => "Georgia"],
        "GEO" => ["flag" => "🇬🇪", "name" => "Georgia"],
        "DE"  => ["flag" => "🇩🇪", "name" => "Germany"],
        "DEU" => ["flag" => "🇩🇪", "name" => "Germany"],
        "GH"  => ["flag" => "🇬🇭", "name" => "Ghana"],
        "GHA" => ["flag" => "🇬🇭", "name" => "Ghana"],
        "GI"  => ["flag" => "🇬🇮", "name" => "Gibraltar"],
        "GIB" => ["flag" => "🇬🇮", "name" => "Gibraltar"],
        "GR"  => ["flag" => "🇬🇷", "name" => "Greece"],
        "GRC" => ["flag" => "🇬🇷", "name" => "Greece"],
        "GS"  => ["flag" => "🇬🇸", "name" => "South Georgia and the South Sandwich Islands"],
        "SGS" => ["flag" => "🇬🇸", "name" => "South Georgia and the South Sandwich Islands"],
        "GL"  => ["flag" => "🇬🇱", "name" => "Greenland"],
        "GRL" => ["flag" => "🇬🇱", "name" => "Greenland"],
        "GD"  => ["flag" => "🇬🇩", "name" => "Grenada"],
        "GRD" => ["flag" => "🇬🇩", "name" => "Grenada"],
        "GP"  => ["flag" => "🇬🇵", "name" => "Guadeloupe"],
        "GLP" => ["flag" => "🇬🇵", "name" => "Guadeloupe"],
        "GU"  => ["flag" => "🇬🇺", "name" => "Guam"],
        "GUM" => ["flag" => "🇬🇺", "name" => "Guam"],
        "GT"  => ["flag" => "🇬🇹", "name" => "Guatemala"],
        "GTM" => ["flag" => "🇬🇹", "name" => "Guatemala"],
        "GW"  => ["flag" => "🇬🇼", "name" => "Guinea-Bissau"],
        "GNB" => ["flag" => "🇬🇼", "name" => "Guinea-Bissau"],
        "GY"  => ["flag" => "🇬🇾", "name" => "Guyana"],
        "GUY" => ["flag" => "🇬🇾", "name" => "Guyana"],
        "HT"  => ["flag" => "🇭🇹", "name" => "Haiti"],
        "HTI" => ["flag" => "🇭🇹", "name" => "Haiti"],
        "HN"  => ["flag" => "🇭🇳", "name" => "Honduras"],
        "HND" => ["flag" => "🇭🇳", "name" => "Honduras"],
        "HM"  => ["flag" => "🇭🇲", "name" => "Heard Island and McDonald Islands"],
        "HMD" => ["flag" => "🇭🇲", "name" => "Heard Island and McDonald Islands"],
        "HU"  => ["flag" => "🇭🇺", "name" => "Hungary"],
        "HUN" => ["flag" => "🇭🇺", "name" => "Hungary"],
        "IS"  => ["flag" => "🇮🇸", "name" => "Iceland"],
        "ISL" => ["flag" => "🇮🇸", "name" => "Iceland"],
        "IN"  => ["flag" => "🇮🇳", "name" => "India"],
        "IND" => ["flag" => "🇮🇳", "name" => "India"],
        "ID"  => ["flag" => "🇮🇩", "name" => "Indonesia"],
        "IDN" => ["flag" => "🇮🇩", "name" => "Indonesia"],
        "IR"  => ["flag" => "🇮🇷", "name" => "Iran (Islamic Republic of)"],
        "IRN" => ["flag" => "🇮🇷", "name" => "Iran (Islamic Republic of)"],
        "IQ"  => ["flag" => "🇮🇶", "name" => "Iraq"],
        "IRQ" => ["flag" => "🇮🇶", "name" => "Iraq"],
        "IE"  => ["flag" => "🇮🇪", "name" => "Ireland"],
        "IRL" => ["flag" => "🇮🇪", "name" => "Ireland"],
        "IL"  => ["flag" => "🇮🇱", "name" => "Israel"],
        "ISR" => ["flag" => "🇮🇱", "name" => "Israel"],
        "IM"  => ["flag" => "🇮🇲", "name" => "Isle of Man"],
        "IMN" => ["flag" => "🇮🇲", "name" => "Isle of Man"],
        "IT"  => ["flag" => "🇮🇹", "name" => "Italy"],
        "ITA" => ["flag" => "🇮🇹", "name" => "Italy"],
        "IO"  => ["flag" => "🇮🇴", "name" => "British Indian Ocean Territory"],
        "IOT" => ["flag" => "🇮🇴", "name" => "British Indian Ocean Territory"],
        "JE"  => ["flag" => "🇯🇪", "name" => "Jersey"],
        "JEY" => ["flag" => "🇯🇪", "name" => "Jersey"],
        "JM"  => ["flag" => "🇯🇲", "name" => "Jamaica"],
        "JAM" => ["flag" => "🇯🇲", "name" => "Jamaica"],
        "JP"  => ["flag" => "🇯🇵", "name" => "Japan"],
        "JPN" => ["flag" => "🇯🇵", "name" => "Japan"],
        "JO"  => ["flag" => "🇯🇴", "name" => "Jordan"],
        "JOR" => ["flag" => "🇯🇴", "name" => "Jordan"],
        "KZ"  => ["flag" => "🇰🇿", "name" => "Kazakhstan"],
        "KAZ" => ["flag" => "🇰🇿", "name" => "Kazakhstan"],
        "KE"  => ["flag" => "🇰🇪", "name" => "Kenya"],
        "KEN" => ["flag" => "🇰🇪", "name" => "Kenya"],
        "KI"  => ["flag" => "🇰🇮", "name" => "Kiribati"],
        "KIR" => ["flag" => "🇰🇮", "name" => "Kiribati"],
        "KP"  => ["flag" => "🇰🇵", "name" => "North Korea"],
        "PRK" => ["flag" => "🇰🇵", "name" => "North Korea"],
        "KR"  => ["flag" => "🇰🇷", "name" => "South Korea"],
        "KOR" => ["flag" => "🇰🇷", "name" => "South Korea"],
        "KW"  => ["flag" => "🇰🇼", "name" => "Kuwait"],
        "KWT" => ["flag" => "🇰🇼", "name" => "Kuwait"],
        "KY"  => ["flag" => "🇰🇾", "name" => "Cayman Islands"],
        "CYM" => ["flag" => "🇰🇾", "name" => "Cayman Islands"],
        "KG"  => ["flag" => "🇰🇬", "name" => "Kyrgyzstan"],
        "KGZ" => ["flag" => "🇰🇬", "name" => "Kyrgyzstan"],
        "LA"  => ["flag" => "🇱🇦", "name" => "Lao PDR"],
        "LAO" => ["flag" => "🇱🇦", "name" => "Lao PDR"],
        "LV"  => ["flag" => "🇱🇻", "name" => "Latvia"],
        "LVA" => ["flag" => "🇱🇻", "name" => "Latvia"],
        "LB"  => ["flag" => "🇱🇧", "name" => "Lebanon"],
        "LBN" => ["flag" => "🇱🇧", "name" => "Lebanon"],
        "LS"  => ["flag" => "🇱🇸", "name" => "Lesotho"],
        "LSO" => ["flag" => "🇱🇸", "name" => "Lesotho"],
        "LR"  => ["flag" => "🇱🇷", "name" => "Liberia"],
        "LBR" => ["flag" => "🇱🇷", "name" => "Liberia"],
        "LY"  => ["flag" => "🇱🇾", "name" => "Libya"],
        "LBY" => ["flag" => "🇱🇾", "name" => "Libya"],
        "LI"  => ["flag" => "🇱🇮", "name" => "Liechtenstein"],
        "LIE" => ["flag" => "🇱🇮", "name" => "Liechtenstein"],
        "LT"  => ["flag" => "🇱🇹", "name" => "Lithuania"],
        "LTU" => ["flag" => "🇱🇹", "name" => "Lithuania"],
        "LU"  => ["flag" => "🇱🇺", "name" => "Luxembourg"],
        "LUX" => ["flag" => "🇱🇺", "name" => "Luxembourg"],
        "MG"  => ["flag" => "🇲🇬", "name" => "Madagascar"],
        "MDG" => ["flag" => "🇲🇬", "name" => "Madagascar"],
        "MW"  => ["flag" => "🇲🇼", "name" => "Malawi"],
        "MWI" => ["flag" => "🇲🇼", "name" => "Malawi"],
        "MY"  => ["flag" => "🇲🇾", "name" => "Malaysia"],
        "MYS" => ["flag" => "🇲🇾", "name" => "Malaysia"],
        "MV"  => ["flag" => "🇲🇻", "name" => "Maldives"],
        "MDV" => ["flag" => "🇲🇻", "name" => "Maldives"],
        "ML"  => ["flag" => "🇲🇱", "name" => "Mali"],
        "MLI" => ["flag" => "🇲🇱", "name" => "Mali"],
        "MT"  => ["flag" => "🇲🇹", "name" => "Malta"],
        "MLT" => ["flag" => "🇲🇹", "name" => "Malta"],
        "MH"  => ["flag" => "🇲🇭", "name" => "Marshall Islands"],
        "MHL" => ["flag" => "🇲🇭", "name" => "Marshall Islands"],
        "MQ"  => ["flag" => "🇲🇶", "name" => "Martinique"],
        "MTQ" => ["flag" => "🇲🇶", "name" => "Martinique"],
        "MR"  => ["flag" => "🇲🇷", "name" => "Mauritania"],
        "MRT" => ["flag" => "🇲🇷", "name" => "Mauritania"],
        "MU"  => ["flag" => "🇲🇺", "name" => "Mauritius"],
        "MUS" => ["flag" => "🇲🇺", "name" => "Mauritius"],
        "MX"  => ["flag" => "🇲🇽", "name" => "Mexico"],
        "MEX" => ["flag" => "🇲🇽", "name" => "Mexico"],
        "FM"  => ["flag" => "🇫🇲", "name" => "Micronesia, Federated States of"],
        "FSM" => ["flag" => "🇫🇲", "name" => "Micronesia, Federated States of"],
        "MD"  => ["flag" => "🇲🇩", "name" => "Moldova"],
        "MDA" => ["flag" => "🇲🇩", "name" => "Moldova"],
        "MC"  => ["flag" => "🇲🇨", "name" => "Monaco"],
        "MCO" => ["flag" => "🇲🇨", "name" => "Monaco"],
        "MN"  => ["flag" => "🇲🇳", "name" => "Mongolia"],
        "MNG" => ["flag" => "🇲🇳", "name" => "Mongolia"],
        "ME"  => ["flag" => "🇲🇪", "name" => "Montenegro"],
        "MNE" => ["flag" => "🇲🇪", "name" => "Montenegro"],
        "MF"  => ["flag" => "🇲🇫", "name" => "Saint Martin"],
        "MAF" => ["flag" => "🇲🇫", "name" => "Saint Martin"],
        "MS"  => ["flag" => "🇲🇸", "name" => "Montserrat"],
        "MSR" => ["flag" => "🇲🇸", "name" => "Montserrat"],
        "MA"  => ["flag" => "🇲🇦", "name" => "Morocco"],
        "MAR" => ["flag" => "🇲🇦", "name" => "Morocco"],
        "MZ"  => ["flag" => "🇲🇿", "name" => "Mozambique"],
        "MOZ" => ["flag" => "🇲🇿", "name" => "Mozambique"],
        "MM"  => ["flag" => "🇲🇲", "name" => "Myanmar"],
        "MMR" => ["flag" => "🇲🇲", "name" => "Myanmar"],
        "MK"  => ["flag" => "🇲🇰", "name" => "North Macedonia"],
        "MKD" => ["flag" => "🇲🇰", "name" => "North Macedonia"],
        "MP"  => ["flag" => "🇲🇵", "name" => "Northern Mariana Islands"],
        "MNP" => ["flag" => "🇲🇵", "name" => "Northern Mariana Islands"],
        "NA"  => ["flag" => "🇳🇦", "name" => "Namibia"],
        "NAM" => ["flag" => "🇳🇦", "name" => "Namibia"],
        "NC"  => ["flag" => "🇳🇨", "name" => "New Caledonia"],
        "NCL" => ["flag" => "🇳🇨", "name" => "New Caledonia"],
        "NR"  => ["flag" => "🇳🇷", "name" => "Nauru"],
        "NRU" => ["flag" => "🇳🇷", "name" => "Nauru"],
        "NU"  => ["flag" => "🇳🇺", "name" => "Niue"],
        "NIU" => ["flag" => "🇳🇺", "name" => "Niue"],
        "NP"  => ["flag" => "🇳🇵", "name" => "Nepal"],
        "NPL" => ["flag" => "🇳🇵", "name" => "Nepal"],
        "NL"  => ["flag" => "🇳🇱", "name" => "Netherlands"],
        "NLD" => ["flag" => "🇳🇱", "name" => "Netherlands"],
        "NZ"  => ["flag" => "🇳🇿", "name" => "New Zealand"],
        "NZL" => ["flag" => "🇳🇿", "name" => "New Zealand"],
        "NI"  => ["flag" => "🇳🇮", "name" => "Nicaragua"],
        "NIC" => ["flag" => "🇳🇮", "name" => "Nicaragua"],
        "NE"  => ["flag" => "🇳🇪", "name" => "Niger"],
        "NER" => ["flag" => "🇳🇪", "name" => "Niger"],
        "NF"  => ["flag" => "🇳🇫", "name" => "Norfolk Island"],
        "NFK" => ["flag" => "🇳🇫", "name" => "Norfolk Island"],
        "NG"  => ["flag" => "🇳🇬", "name" => "Nigeria"],
        "NGA" => ["flag" => "🇳🇬", "name" => "Nigeria"],
        "NO"  => ["flag" => "🇳🇴", "name" => "Norway"],
        "NOR" => ["flag" => "🇳🇴", "name" => "Norway"],
        "OM"  => ["flag" => "🇴🇲", "name" => "Oman"],
        "OMN" => ["flag" => "🇴🇲", "name" => "Oman"],
        "PK"  => ["flag" => "🇵🇰", "name" => "Pakistan"],
        "PAK" => ["flag" => "🇵🇰", "name" => "Pakistan"],
        "PW"  => ["flag" => "🇵🇼", "name" => "Palau"],
        "PLW" => ["flag" => "🇵🇼", "name" => "Palau"],
        "PS"  => ["flag" => "🇵🇸", "name" => "Palestinian Territory"],
        "PSE" => ["flag" => "🇵🇸", "name" => "Palestinian Territory"],
        "PA"  => ["flag" => "🇵🇦", "name" => "Panama"],
        "PAN" => ["flag" => "🇵🇦", "name" => "Panama"],
        "PG"  => ["flag" => "🇵🇬", "name" => "Papua New Guinea"],
        "PNG" => ["flag" => "🇵🇬", "name" => "Papua New Guinea"],
        "PY"  => ["flag" => "🇵🇾", "name" => "Paraguay"],
        "PRY" => ["flag" => "🇵🇾", "name" => "Paraguay"],
        "PE"  => ["flag" => "🇵🇪", "name" => "Peru"],
        "PER" => ["flag" => "🇵🇪", "name" => "Peru"],
        "PH"  => ["flag" => "🇵🇭", "name" => "Philippines"],
        "PHL" => ["flag" => "🇵🇭", "name" => "Philippines"],
        "PL"  => ["flag" => "🇵🇱", "name" => "Poland"],
        "POL" => ["flag" => "🇵🇱", "name" => "Poland"],
        "PM"  => ["flag" => "🇵🇲", "name" => "Saint Pierre and Miquelon"],
        "SPM" => ["flag" => "🇵🇲", "name" => "Saint Pierre and Miquelon"],
        "PN"  => ["flag" => "🇵🇳", "name" => "Pitcairn"],
        "PCN" => ["flag" => "🇵🇳", "name" => "Pitcairn"],
        "PT"  => ["flag" => "🇵🇹", "name" => "Portugal"],
        "PRT" => ["flag" => "🇵🇹", "name" => "Portugal"],
        "PR"  => ["flag" => "🇵🇷", "name" => "Puerto Rico"],
        "PRI" => ["flag" => "🇵🇷", "name" => "Puerto Rico"],
        "QA"  => ["flag" => "🇶🇦", "name" => "Qatar"],
        "QAT" => ["flag" => "🇶🇦", "name" => "Qatar"],
        "RE"  => ["flag" => "🇷🇪", "name" => "Réunion"],
        "REU" => ["flag" => "🇷🇪", "name" => "Réunion"],
        "RO"  => ["flag" => "🇷🇴", "name" => "Romania"],
        "ROU" => ["flag" => "🇷🇴", "name" => "Romania"],
        "RU"  => ["flag" => "🇷🇺", "name" => "Russian Federation"],
        "RUS" => ["flag" => "🇷🇺", "name" => "Russian Federation"],
        "RW"  => ["flag" => "🇷🇼", "name" => "Rwanda"],
        "RWA" => ["flag" => "🇷🇼", "name" => "Rwanda"],
        "KN"  => ["flag" => "🇰🇳", "name" => "Saint Kitts and Nevis"],
        "KNA" => ["flag" => "🇰🇳", "name" => "Saint Kitts and Nevis"],
        "LC"  => ["flag" => "🇱🇨", "name" => "Saint Lucia"],
        "LCA" => ["flag" => "🇱🇨", "name" => "Saint Lucia"],
        "VC"  => ["flag" => "🇻🇨", "name" => "Saint Vincent and Grenadines"],
        "VCT" => ["flag" => "🇻🇨", "name" => "Saint Vincent and Grenadines"],
        "WS"  => ["flag" => "🇼🇸", "name" => "Samoa"],
        "WSM" => ["flag" => "🇼🇸", "name" => "Samoa"],
        "SM"  => ["flag" => "🇸🇲", "name" => "San Marino"],
        "SMR" => ["flag" => "🇸🇲", "name" => "San Marino"],
        "ST"  => ["flag" => "🇸🇹", "name" => "Sao Tome and Principe"],
        "STP" => ["flag" => "🇸🇹", "name" => "Sao Tome and Principe"],
        "SA"  => ["flag" => "🇸🇦", "name" => "Saudi Arabia"],
        "SAU" => ["flag" => "🇸🇦", "name" => "Saudi Arabia"],
        "SN"  => ["flag" => "🇸🇳", "name" => "Senegal"],
        "SEN" => ["flag" => "🇸🇳", "name" => "Senegal"],
        "RS"  => ["flag" => "🇷🇸", "name" => "Serbia"],
        "SRB" => ["flag" => "🇷🇸", "name" => "Serbia"],
        "SC"  => ["flag" => "🇸🇨", "name" => "Seychelles"],
        "SYC" => ["flag" => "🇸🇨", "name" => "Seychelles"],
        "SL"  => ["flag" => "🇸🇱", "name" => "Sierra Leone"],
        "SLE" => ["flag" => "🇸🇱", "name" => "Sierra Leone"],
        "SG"  => ["flag" => "🇸🇬", "name" => "Singapore"],
        "SGP" => ["flag" => "🇸🇬", "name" => "Singapore"],
        "SH"  => ["flag" => "🇸🇭", "name" => "Saint Helena, Ascension and Tristan da Cunha"],
        "SHN" => ["flag" => "🇸🇭", "name" => "Saint Helena, Ascension and Tristan da Cunha"],
        "SK"  => ["flag" => "🇸🇰", "name" => "Slovakia"],
        "SVK" => ["flag" => "🇸🇰", "name" => "Slovakia"],
        "SI"  => ["flag" => "🇸🇮", "name" => "Slovenia"],
        "SVN" => ["flag" => "🇸🇮", "name" => "Slovenia"],
        "SJ"  => ["flag" => "🇸🇯", "name" => "Svalbard and Jan Mayen"],
        "SJM" => ["flag" => "🇸🇯", "name" => "Svalbard and Jan Mayen"],
        "SB"  => ["flag" => "🇸🇧", "name" => "Solomon Islands"],
        "SLB" => ["flag" => "🇸🇧", "name" => "Solomon Islands"],
        "SO"  => ["flag" => "🇸🇴", "name" => "Somalia"],
        "SOM" => ["flag" => "🇸🇴", "name" => "Somalia"],
        "ZA"  => ["flag" => "🇿🇦", "name" => "South Africa"],
        "ZAF" => ["flag" => "🇿🇦", "name" => "South Africa"],
        "ES"  => ["flag" => "🇪🇸", "name" => "Spain"],
        "ESP" => ["flag" => "🇪🇸", "name" => "Spain"],
        "LK"  => ["flag" => "🇱🇰", "name" => "Sri Lanka"],
        "LKA" => ["flag" => "🇱🇰", "name" => "Sri Lanka"],
        "SD"  => ["flag" => "🇸🇩", "name" => "Sudan"],
        "SDN" => ["flag" => "🇸🇩", "name" => "Sudan"],
        "SS"  => ["flag" => "🇸🇸", "name" => "South Sudan"],
        "SSD" => ["flag" => "🇸🇸", "name" => "South Sudan"],
        "SR"  => ["flag" => "🇸🇷", "name" => "Suriname"],
        "SUR" => ["flag" => "🇸🇷", "name" => "Suriname"],
        "SE"  => ["flag" => "🇸🇪", "name" => "Sweden"],
        "SWE" => ["flag" => "🇸🇪", "name" => "Sweden"],
        "CH"  => ["flag" => "🇨🇭", "name" => "Switzerland"],
        "CHE" => ["flag" => "🇨🇭", "name" => "Switzerland"],
        "SY"  => ["flag" => "🇸🇾", "name" => "Syrian"],
        "SYR" => ["flag" => "🇸🇾", "name" => "Syrian"],
        "SZ"  => ["flag" => "🇸🇿", "name" => "Eswatini"],
        "SWZ" => ["flag" => "🇸🇿", "name" => "Eswatini"],
        "TW"  => ["flag" => "🇹🇼", "name" => "Taiwan"],
        "TWN" => ["flag" => "🇹🇼", "name" => "Taiwan"],
        "TC"  => ["flag" => "🇹🇨", "name" => "Turks and Caicos Islands"],
        "TCA" => ["flag" => "🇹🇨", "name" => "Turks and Caicos Islands"],
        "TF"  => ["flag" => "🇹🇫", "name" => "French Southern Territories"],
        "ATF" => ["flag" => "🇹🇫", "name" => "French Southern Territories"],
        "TJ"  => ["flag" => "🇹🇯", "name" => "Tajikistan"],
        "TJK" => ["flag" => "🇹🇯", "name" => "Tajikistan"],
        "TK"  => ["flag" => "🇹🇰", "name" => "Tokelau"],
        "TKL" => ["flag" => "🇹🇰", "name" => "Tokelau"],
        "TZ"  => ["flag" => "🇹🇿", "name" => "Tanzania"],
        "TZA" => ["flag" => "🇹🇿", "name" => "Tanzania"],
        "TH"  => ["flag" => "🇹🇭", "name" => "Thailand"],
        "THA" => ["flag" => "🇹🇭", "name" => "Thailand"],
        "TG"  => ["flag" => "🇹🇬", "name" => "Togo"],
        "TGO" => ["flag" => "🇹🇬", "name" => "Togo"],
        "TO"  => ["flag" => "🇹🇴", "name" => "Tonga"],
        "TON" => ["flag" => "🇹🇴", "name" => "Tonga"],
        "TT"  => ["flag" => "🇹🇹", "name" => "Trinidad and Tobago"],
        "TTO" => ["flag" => "🇹🇹", "name" => "Trinidad and Tobago"],
        "TN"  => ["flag" => "🇹🇳", "name" => "Tunisia"],
        "TUN" => ["flag" => "🇹🇳", "name" => "Tunisia"],
        "TR"  => ["flag" => "🇹🇷", "name" => "Turkey"],
        "TUR" => ["flag" => "🇹🇷", "name" => "Turkey"],
        "TM"  => ["flag" => "🇹🇲", "name" => "Turkmenistan"],
        "TKM" => ["flag" => "🇹🇲", "name" => "Turkmenistan"],
        "TL"  => ["flag" => "🇹🇱", "name" => "Timor-Leste"],
        "TLS" => ["flag" => "🇹🇱", "name" => "Timor-Leste"],
        "TV"  => ["flag" => "🇹🇻", "name" => "Tuvalu"],
        "TUV" => ["flag" => "🇹🇻", "name" => "Tuvalu"],
        "UG"  => ["flag" => "🇺🇬", "name" => "Uganda"],
        "UGA" => ["flag" => "🇺🇬", "name" => "Uganda"],
        "UM"  => ["flag" => "🇺🇲", "name" => "United States Minor Outlying Islands"],
        "UMI" => ["flag" => "🇺🇲", "name" => "United States Minor Outlying Islands"],
        "UA"  => ["flag" => "🇺🇦", "name" => "Ukraine"],
        "UKR" => ["flag" => "🇺🇦", "name" => "Ukraine"],
        "AE"  => ["flag" => "🇦🇪", "name" => "United Arab Emirates"],
        "ARE" => ["flag" => "🇦🇪", "name" => "United Arab Emirates"],
        "GB"  => ["flag" => "🇬🇧", "name" => "United Kingdom"],
        "GBR" => ["flag" => "🇬🇧", "name" => "United Kingdom"],
        "US"  => ["flag" => "🇺🇸", "name" => "United States"],
        "USA" => ["flag" => "🇺🇸", "name" => "United States"],
        "UY"  => ["flag" => "🇺🇾", "name" => "Uruguay"],
        "URY" => ["flag" => "🇺🇾", "name" => "Uruguay"],
        "UZ"  => ["flag" => "🇺🇿", "name" => "Uzbekistan"],
        "UZB" => ["flag" => "🇺🇿", "name" => "Uzbekistan"],
        "VA"  => ["flag" => "🇻🇦", "name" => "Holy See"],
        "VAT" => ["flag" => "🇻🇦", "name" => "Holy See"],
        "VU"  => ["flag" => "🇻🇺", "name" => "Vanuatu"],
        "VUT" => ["flag" => "🇻🇺", "name" => "Vanuatu"],
        "VE"  => ["flag" => "🇻🇪", "name" => "Venezuela"],
        "VEN" => ["flag" => "🇻🇪", "name" => "Venezuela"],
        "VI"  => ["flag" => "🇻🇮", "name" => "U.S. Virgin Islands"],
        "VIR" => ["flag" => "🇻🇮", "name" => "U.S. Virgin Islands"],
        "VN"  => ["flag" => "🇻🇳", "name" => "Viet Nam"],
        "VNM" => ["flag" => "🇻🇳", "name" => "Viet Nam"],
        "WF"  => ["flag" => "🇼🇫", "name" => "Wallis and Futuna"],
        "WLF" => ["flag" => "🇼🇫", "name" => "Wallis and Futuna"],
        "YE"  => ["flag" => "🇾🇪", "name" => "Yemen"],
        "YEM" => ["flag" => "🇾🇪", "name" => "Yemen"],
        "YT"  => ["flag" => "🇾🇹", "name" => "Mayotte"],
        "MYT" => ["flag" => "🇾🇹", "name" => "Mayotte"],
        "ZM"  => ["flag" => "🇿🇲", "name" => "Zambia"],
        "ZMB" => ["flag" => "🇿🇲", "name" => "Zambia"],
        "ZW"  => ["flag" => "🇿🇼", "name" => "Zimbabwe"],
        "ZWE" => ["flag" => "🇿🇼", "name" => "Zimbabwe"],
        "XK"  => ["flag" => "🇽🇰", "name" => "Kosovo"],
        "XKS" => ["flag" => "🇽🇰", "name" => "Kosovo"],
    ];



    static function alpha2toalpha3(string $code): ?string
    {
        static $map = null;

        $code = strtoupper($code);
        if (strlen($code) !== 2) {
            return null;
        }

        if ($map === null) {
            $map = [];
            foreach (self::$countries as $isoCode => $details) {
                if (strlen($isoCode) === 3) {
                    $map[$details['name']] = $isoCode;
                }
            }
        }

        $country = self::getByCode($code);
        return $country && isset($map[$country['name']]) ? $map[$country['name']] : null;
    }

    static function getAll(): array
    {
        return self::$countries;
    }

    static function getByCode(string $code): ?array
    {
        $code = strtoupper($code);
        return self::$countries[$code] ?? null;
    }

    static function getByName(string $name): ?array
    {
        foreach (self::$countries as $country) {
            if (strtolower($country['name']) === strtolower($name)) {
                return $country;
            }
        }
        return null;
    }

    static function nameWithFlag(string $code): ?string
    {
        $country = self::getByCode($code);
        if ($country) {
            return $country['flag'] . ' ' . $country['name'];
        }
        return null;
    }


}
